
<footer class="footer social_media">
   	 	<div class="meida">
            
			<p class="round"><a href="https://www.facebook.com/Maxani-215188869146896/?view_public_for=215188869146896" class="facebook"><svg viewBox="0 0 24 24"><path d="M19,4V7H17A1,1 0 0,0 16,8V10H19V13H16V20H13V13H11V10H13V7.5C13,5.56 14.57,4 16.5,4M20,2H4A2,2 0 0,0 2,4V20A2,2 0 0,0 4,22H20A2,2 0 0,0 22,20V4C22,2.89 21.1,2 20,2Z"></path></svg></a></p>
      
      <p class="round"><a href="https://twitter.com/maxani123" class="twitter"><svg viewBox="0 0 24 24"><path d="M17.71,9.33C17.64,13.95 14.69,17.11 10.28,17.31C8.46,17.39 7.15,16.81 6,16.08C7.34,16.29 9,15.76 9.9,15C8.58,14.86 7.81,14.19 7.44,13.12C7.82,13.18 8.22,13.16 8.58,13.09C7.39,12.69 6.54,11.95 6.5,10.41C6.83,10.57 7.18,10.71 7.64,10.74C6.75,10.23 6.1,8.38 6.85,7.16C8.17,8.61 9.76,9.79 12.37,9.95C11.71,7.15 15.42,5.63 16.97,7.5C17.63,7.38 18.16,7.14 18.68,6.86C18.47,7.5 18.06,7.97 17.56,8.33C18.1,8.26 18.59,8.13 19,7.92C18.75,8.45 18.19,8.93 17.71,9.33M20,2H4A2,2 0 0,0 2,4V20A2,2 0 0,0 4,22H20A2,2 0 0,0 22,20V4C22,2.89 21.1,2 20,2Z"></path></svg></a></p>
     
            
		  </div>
   </footer>

</body>
</html>
  <script type="text/javascript">
$(document).ready(function(){
  var data = [  
  {
  "title_anime" :"Late Night! The Genius Bakabon",
  "episode" :6,
  "image" :"anime_image/Late Night! The Genius Bakabon.jpg",
    "url" : "anime-html/Late Night! The Genius Bakabon-main/Late Night! The Genius Bakabon-main.php",
    "gener" : "",
},

 {
  "title_anime" :"Angolmois Genkou Kassenki",
  "episode" :6,
  "image" :"anime_image/Angolmois Genkou Kassenki.jpg",
    "url" : "anime-html/Angolmois Genkou Kassenki-main/Angolmois Genkou Kassenki-main.php",
    "gener" : "",
},
{
  "title_anime" :"Iya na Kao sare nagara Opantsu Misete Moraitai",
  "image" :"anime_image/Iya na Kao sare nagara Opantsu Misete Moraitai.jpg",
    "url" : "anime-html/Iya na Kao sare nagara Opantsu Misete Moraitai-main/Iya na Kao sare nagara Opantsu Misete Moraitai-main.php",
    "gener" : "",
},
{
  "title_anime" :"Double Decker! Doug & Kirill",
  "image" :"anime_image/Double Decker! Doug & Kirill.jpg",
    "url" : "anime-html/Double Decker! Doug & Kirill-main/Double Decker! Doug & Kirill-main.php",
    "gener" : "",
},
{
  "title_anime" :"Inazuma Eleven Orion no Kokuin",
  "image" :"anime_image/Inazuma Eleven Orion no Kokuin.jpg",
    "url" : "anime-html/Inazuma Eleven Orion no Kokuin-main/Inazuma Eleven Orion no Kokuin-main.php",
    "gener" : "",
},
{
  "title_anime" :"Fairy Tail (2018)",
  "image" :"anime_image/Fairy Tail (2018).jpg",
    "url" : "anime-html/Fairy Tail (2018)-main/Fairy Tail (2018)-main.php",
    "gener" : "",
},
{
  "title_anime" :"Otona no Bouguya-san",
  "image" :"anime_image/Otona no Bouguya-san.jpg",
    "url" : "anime-html/Otona no Bouguya-san-main/Otona no Bouguya-san-main.php",
    "gener" : "",
},
{
  "title_anime" :"SSSS.Gridman",
  "image" :"anime_image/SSSS.Gridman.jpg",
    "url" : "anime-html/SSSS.Gridman-main/SSSS.Gridman-main.php",
    "gener" : "",
},
{
  "title_anime" :"JoJo no Kimyou na Bouken Ougon no Kaze",
  "image" :"anime_image/JoJo no Kimyou na Bouken Ougon no Kaze.jpg",
    "url" : "anime-html/JoJo no Kimyou na Bouken Ougon no Kaze-main/JoJo no Kimyou na Bouken Ougon no Kaze-main.php",
    "gener" : "",
},
{
  "title_anime" :"Kaze ga Tsuyoku Fuiteiru",
  "image" :"anime_image/Kaze ga Tsuyoku Fuiteiru.jpg",
    "url" : "anime-html/Kaze ga Tsuyoku Fuiteiru-main/Kaze ga Tsuyoku Fuiteiru-main.php",
    "gener" : "",
},
{
  "title_anime" :"Radiant",
  "image" :"anime_image/Radiant.jpg",
    "url" : "anime-html/Radiant-main/Radiant-main.php",
    "gener" : "",
},
{
  "title_anime" :"Toaru Majutsu no Index III",
  "image" :"anime_image/Toaru Majutsu no Index III.jpg",
    "url" : "anime-html/Toaru Majutsu no Index III-main/Toaru Majutsu no Index III-main.php",
    "gener" : "",
},
{
  "title_anime" :"Gakuen Basara",
  "image" :"anime_image/Gakuen Basara.jpg",
    "url" : "anime-html/Gakuen Basara-main/Gakuen Basara-main.php",
    "gener" : "",
},
{
  "title_anime" :"Senran Kagura Shinovi Master Tokyo Youma-hen",
  "image" :"anime_image/Senran Kagura Shinovi Master Tokyo Youma-hen.jpg",
    "url" : "anime-html/Senran Kagura Shinovi Master Tokyo Youma-hen-main/Senran Kagura Shinovi Master Tokyo Youma-hen-main.php",
    "gener" : "",
},
{
  "title_anime" :"Kishuku Gakkou no Juliet",
  "image" :"anime_image/Kishuku Gakkou no Juliet.jpg",
    "url" : "anime-html/Kishuku Gakkou no Juliet-main/Kishuku Gakkou no Juliet-main.php",
    "gener" : "",
},
{
  "title_anime" :"Golden Kamuy 2nd Season",
  "image" :"anime_image/Golden Kamuy 2nd Season.jpg",
    "url" : "anime-html/Golden Kamuy 2nd Season-main/Golden Kamuy 2nd Season-main.php",
    "gener" : "",
},
{
  "title_anime" :"Jingai-san no Yome",
  "image" :"anime_image/Jingai-san no Yome.jpg",
    "url" : "anime-html/Jingai-san no Yome-main/Jingai-san no Yome-main.php",
    "gener" : "",
},
{
  "title_anime" :"Gurazeni Season 2",
  "image" :"anime_image/gurazeni.jpg",
    "url" : "anime-html/Gurazeni Season 2-main/Gurazeni Season 2-main.php",
    "gener" : "",
},
{
  "title_anime" :"Goblin Slayer",
  "image" :"anime_image/Goblin Slayer.jpg",
    "url" : "anime-html/Goblin Slayer-main/Goblin Slayer-main.php",
    "gener" : "",
},
{
  "title_anime" :"Zoids Wild",
  "image" :"anime_image/Zoids Wild.jpg",
    "url" : "anime-html/Zoids Wild-main/Zoids Wild-main.php",
    "gener" : "",
},
{
  "title_anime" :"Tokyo Ghoulre 2nd Season",
  "image" :"anime_image/Tokyo Ghoulre 2nd Season.jpg",
    "url" : "anime-html/Tokyo Ghoulre 2nd Season-main/Tokyo Ghoulre 2nd Season-main.php",
    "gener" : "",
},
{
  "title_anime" :"Tensei shitara Slime Datta Ken",
  "image" :"anime_image/Tensei shitara Slime Datta Ken.jpg",
    "url" : "anime-html/Tensei shitara Slime Datta Ken-main/Tensei shitara Slime Datta Ken-main.php",
    "gener" : "",
},
{
  "title_anime" :"Sword Art Online Alicization",
  "image" :"anime_image/Sword Art Online Alicization.jpg",
    "url" : "anime-html/Sword Art Online Alicization-main/Sword Art Online Alicization-main.php",
    "gener" : "",
},
{
  "title_anime" :"Uchi no Maid ga Uzasugiru!",
  "image" :"anime_image/Uchi no Maid ga Uzasugiru!.jpg",
    "url" : "anime-html/Uchi no Maid ga Uzasugiru!-main/Uchi no Maid ga Uzasugiru!-main.php",
    "gener" : "",
},
{
  "title_anime" :"Dakaretai Otoko 1-i ni Odosarete Imasu.",
  "image" :"anime_image/Dakaretai Otoko 1-i ni Odosarete Imasu..jpg",
    "url" : "anime-html/Dakaretai Otoko 1-i ni Odosarete Imasu.-main/Dakaretai Otoko 1-i ni Odosarete Imasu.-main.php",
    "gener" : "",
},
{
  "title_anime" :"Irozuku Sekai no Ashita kara",
  "image" :"anime_image/Irozuku Sekai no Ashita kara.jpg",
    "url" : "anime-html/Irozuku Sekai no Ashita kara-main/Irozuku Sekai no Ashita kara-main.php",
    "gener" : "",
},
{
  "title_anime" :"Kirakira Happy Hirake! Cocotama",
  "image" :"anime_image/Kirakira Happy Hirake! Cocotama.jpg",
    "url" : "anime-html/Kirakira Happy Hirake! Cocotama-main/Kirakira Happy Hirake! Cocotama-main.php",
    "gener" : "",
},
{
  "title_anime" :"Beelzebub-jou no Okinimesu mama",
  "image" :"anime_image/Beelzebub-jou no Okinimesu mama.jpg",
    "url" : "anime-html/Beelzebub-jou no Okinimesu mama-main/Beelzebub-jou no Okinimesu mama-main.php",
    "gener" : "",
},
{
  "title_anime" :"Conception",
  "image" :"anime_image/Conception.jpg",
    "url" : "anime-html/Conception-main/Conception-main.php",
    "gener" : "",
},
{
  "title_anime" :"Ore ga Suki nano wa Imouto dakedo Imouto ja Nai",
  "image" :"anime_image/Ore ga Suki nano wa Imouto dakedo Imouto ja Nai.jpg",
    "url" : "anime-html/Ore ga Suki nano wa Imouto dakedo Imouto ja Nai-main/Ore ga Suki nano wa Imouto dakedo Imouto ja Nai-main.php",
    "gener" : "",
},
{
  "title_anime" :"Karakuri Circus",
  "image" :"anime_image/Karakuri Circus.jpg",
    "url" : "anime-html/Karakuri Circus-main/Karakuri Circus-main.php",
    "gener" : "",
},
{
  "title_anime" :"Hora, Mimi ga Mieteru yo!",
  "image" :"anime_image/Hora, Mimi ga Mieteru yo!.jpg",
    "url" : "anime-html/Hora, Mimi ga Mieteru yo!-main/Hora, Mimi ga Mieteru yo!-main.php",
    "gener" : "",
},
{
  "title_anime" :"BanG Dream! Garupa Pico",
  "image" :"anime_image/BanG Dream! Garupa Pico.jpg",
    "url" : "anime-html/BanG Dream! Garupa Pico-main/BanG Dream! Garupa Pico-main.php",
    "gener" : "",
},
{
  "title_anime" :"Merc Storia Mukiryoku no Shounen to Bin no Naka no Shoujo",
  "image" :"anime_image/Merc Storia Mukiryoku no Shounen to Bin no Naka no Shoujo.jpg",
    "url" : "anime-html/Merc Storia Mukiryoku no Shounen to Bin no Naka no Shoujo-main/Merc Storia Mukiryoku no Shounen to Bin no Naka no Shoujo-main.php",
    "gener" : "",
},
{
  "title_anime" :"Gegege no Kitarou (2018)",
  "image" :"anime_image/Gegege no Kitarou (2018).jpg",
    "url" : "anime-html/Gegege no Kitarou (2018)-main/Gegege no Kitarou (2018)-main.php",
    "gener" : "",
},
{
  "title_anime" :"Hinomaruzumou",
  "image" :"anime_image/Hinomaruzumou.jpg",
    "url" : "anime-html/Hinomaruzumou-main/Hinomaruzumou-main.php",
    "gener" : "",
},
{
  "title_anime" :"Sora to Umi no Aida",
  "image" :"anime_image/Sora to Umi no Aida.jpg",
    "url" : "anime-html/Sora to Umi no Aida-main/Sora to Umi no Aida-main.php",
    "gener" : "",
},
{
  "title_anime" :"Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai",
  "image" :"anime_image/Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai.jpg",
    "url" : "anime-html/Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai-main/Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai-main.php",
    "gener" : "",
},
{
  "title_anime" :"Bakumatsu",
  "image" :"anime_image/Bakumatsu.jpg",
    "url" : "anime-html/Bakumatsu-main/Bakumatsu-main.php",
    "gener" : "",
},
{
  "title_anime" :"Zombieland Saga",
  "image" :"anime_image/Zombieland Saga.jpg",
    "url" : "anime-html/Zombieland Saga-main/Zombieland Saga-main.php",
    "gener" : "",
},
{
  "title_anime" :"Yagate Kimi ni Naru",
  "image" :"anime_image/Yagate Kimi ni Naru.jpg",
    "url" : "anime-html/Yagate Kimi ni Naru-main/Yagate Kimi ni Naru-main.php",
    "gener" : "",
},
{
  "title_anime" :"Tonari no Kyuuketsuki-san",
  "image" :"anime_image/Tonari no Kyuuketsuki-san.jpg",
    "url" : "anime-html/Tonari no Kyuuketsuki-san-main/Tonari no Kyuuketsuki-san-main.php",
    "gener" : "",
},
{
  "title_anime" :"Sheng Shi Zhuang Niang",
  "image" :"anime_image/Sheng Shi Zhuang Niang.jpg",
    "url" : "anime-html/Sheng Shi Zhuang Niang-main/Sheng Shi Zhuang Niang-main.php",
    "gener" : "",
},
{
  "title_anime" :"Masamune-kun no Revenge OVA",
  "image" :"anime_image/Masamune-kun no Revenge OVA.jpg",
    "url" : "anime-html/Masamune-kun no Revenge OVA-main/Masamune-kun no Revenge OVA-main.php",
    "gener" : "",
},
{
  "title_anime" :"Koneko no Chii Ponponraa Dairyokou",
  "image" :"anime_image/Koneko no Chii Ponponraa Dairyokou.jpg",
    "url" : "anime-html/Koneko no Chii Ponponraa Dairyokou-main/Koneko no Chii Ponponraa Dairyokou-main.php",
    "gener" : "",
},
{
  "title_anime" :"Future Card Buddyfight Ace",
  "image" :"anime_image/Future Card Buddyfight Ace.jpg",
    "url" : "anime-html/Future Card Buddyfight Ace-main/Future Card Buddyfight Ace-main.php",
    "gener" : "",
},
{
  "title_anime" :"Ani ni Tsukeru Kusuri wa Nai! 2",
  "image" :"anime_image/Ani ni Tsukeru Kusuri wa Nai! 2.jpg",
    "url" : "anime-html/Ani ni Tsukeru Kusuri wa Nai! 2-main/Ani ni Tsukeru Kusuri wa Nai! 2-main.php",
    "gener" : "",
},
{
  "title_anime" :"RErideD Tokigoe no Derrida",
  "image" :"anime_image/RErideD Tokigoe no Derrida.jpg",
    "url" : "anime-html/RErideD Tokigoe no Derrida-main/RErideD Tokigoe no Derrida-main.php",
    "gener" : "",
},
{
  "title_anime" :"Overlord Ple Ple Pleiades 3",
  "image" :"anime_image/Overlord Ple Ple Pleiades 3.jpg",
    "url" : "anime-html/Overlord Ple Ple Pleiades 3-main/Overlord Ple Ple Pleiades 3-main.php",
    "gener" : "",
},
{
  "title_anime" :"Beatless Final Stage",
  "image" :"anime_image/Beatless Final Stage.jpg",
    "url" : "anime-html/Beatless Final Stage-main/Beatless Final Stage-main.php",
    "gener" : "",
},
{
  "title_anime" :"Senjuushi",
  "image" :"anime_image/Senjuushi.jpg",
    "url" : "anime-html/Senjuushi-main/Senjuushi-main.php",
    "gener" : "",
},
{
  "title_anime" :"Asobi Asobase",
  "episode" :6,
  "image" :"anime_image/Asobi Asobase.jpg",
    "url" : "anime-html/Asobi Asobase-main/Asobi Asobase-main.php",
    "gener" : "",
},
 {
  "title_anime" :"YAMI SHIBAI 6",
  "image" :"anime_image/YAMI SHIBAI 6.jpg",
    "url" : "anime-html/YAMI SHIBAI 6-main/YAMI SHIBAI 6-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Dragon Ball Super",
  "image" :"anime_image/Dragon Ball Super.jpg",
    "url" : "anime-html/Dragon Ball Super-main/Dragon Ball Super-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Hunter X Hunter 2011",
  "image" :"anime_image/Hunter X Hunter 2011.jpg",
    "url" : "anime-html/Hunter X Hunter 2011/Hunter X Hunter 2011-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Juushinki Pandora",
  "image" :"anime_image/Juushinki Pandora.jpg",
    "url" : "anime-html/Juushinki Pandora-main/Juushinki Pandora-main.php",
    "gener" : "",
},

 {
  "title_anime" :"Mo Dao Zu Shi",
  "image" :"anime_image/Mo Dao Zu Shi.jpg",
    "url" : "anime-html/Mo Dao Zu Shi-main/Mo Dao Zu Shi-main.php",
    "gener" : "",
},
 {
  "title_anime" :"high score girl",
  "image" :"anime_image/high score girl.jpg",
    "url" : "anime-html/high score girl-main/high score girl-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Kyoto Teramachi Sanjou no Holmes",
  "image" :"anime_image/Kyoto Teramachi Sanjou no Holmes.jpg",
    "url" : "anime-html/Kyoto Teramachi Sanjou no Holmes-main/Kyoto Teramachi Sanjou no Holmes-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Tenrou Sirius the Jaeger",
  "image" :"anime_image/Tenrou Sirius the Jaeger.jpg",
    "url" : "anime-html/Tenrou Sirius the Jaeger-main/Tenrou Sirius the Jaeger-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Chuukan Kanriroku Tonegawa",
  "image" :"anime_image/Chuukan Kanriroku Tonegawa.jpg",
    "url" : "anime-html/Chuukan Kanriroku Tonegawa-main/Chuukan Kanriroku Tonegawa-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Yama no Susume Third Season",
  "image" :"anime_image/Yama no Susume Third Season.jpg",
    "url" : "anime-html/Yama no Susume Third Season-main/Yama no Susume Third Season-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Attack on Titan",
  "image" :"anime_image/Attack on Titan.jpg",
    "url" : "anime-html/Attack on Titan-main/Attack on Titan-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Attack on Titan Season 2",
  "image" :"anime_image/Attack on Titan Season 2.jpg",
    "url" : "anime-html/Attack on Titan Season 2-main/Attack on Titan Season 2-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Baki (2018)",
  "image" :"anime_image/Baki (2018).jpg",
    "url" : "anime-html/Baki (2018)-main/Baki (2018)-main.php",
    "gener" : "",
},
{
  "title_anime" :"Lord of Vermilion Guren no Ou",
  "episode" :5,
  "image" :"anime_image/Lord of Vermilion Guren no Ou.jpg",
    "url" : "anime-html/Lord of Vermilion Guren no Ou-main/Lord of Vermilion Guren no Ou-main.php",
    "gener" : "",
},
{
  "title_anime" :"Happy Sugar Life",
  "episode" :5,
  "image" :"anime_image/Happy Sugar Life.jpg",
    "url" : "anime-html/Happy Sugar Life-main/Happy Sugar Life-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Boku no Hero Academia",
  "image" :"anime_image/Boku no Hero Academia.jpg",
    "url" : "anime-html/Boku no Hero Academia-main/Boku no Hero Academia-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Prison school ova",
  "image" :"anime_image/Prison school ova.jpg",
    "url" : "anime-html/Prison school ova-main/Prison school ova-main.php",
    "gener" : "",
},
 {
  "title_anime" :"Prison School",
  "image" :"anime_image/Prison School.jpg",
    "url" : "anime-html/Prison School-main/Prison School-main.php",
    "gener" : "",
},
{
  "title_anime" :"Chio-chan no Tsuugakuro",
  "episode" :6,
  "image" :"anime_image/Chio-chan no Tsuugakuro.jpg",
    "url" : "anime-html/Chio-chan no Tsuugakuro-main/Chio-chan no Tsuugakuro-main.php",
    "gener" : "",
},
{
  "title_anime" :"Back Street Girls Gokudolls",
  "episode" :7,
  "image" :"anime_image/Back Street Girls Gokudolls.jpg",
    "url" : "anime-html/Back Street Girls Gokudolls-main/Back Street Girls Gokudolls-main.php",
    "gener" : "",
},
{
  "title_anime" :"One Room 2nd Season",
  "episode" :6,
  "image" :"anime_image/One Room 2nd Season.jpg",
    "url" : "anime-html/One Room 2nd Season-main/One Room 2nd Season-main.php",
    "gener" : "",
},
{
  "title_anime" :"Phantom in the Twilight",
  "episode" :6,
  "image" :"anime_image/Phantom in the Twilight.jpg",
    "url" : "anime-html/Phantom in the Twilight-main/Phantom in the Twilight-main.php",
    "gener" : "",
},
{ 
  "title_anime" :"Naruto Shippuden  ",
  "episode" :500,
  "image" :"anime_image/Naruto Shippuden.jpg",
    "url" : "anime-html/Naruto Shippuden-main/Naruto Shippuden -main.php",
    "gener" : "",
},
{
  "title_anime" :"inazuma  eleven ares  no tenbin",
  "episode" :19,
  "image" :"anime_image/inazuma_eleven.jpg",
    "url" : "anime-html/inazuma  eleven ares  no tenbin-main/inazuma-eleven-ares-no-tenbin-main.php",
    "gener" : "",
},
{
  "title_anime" :"one piece",
  "episode" :849,
  "image" :"anime_image/one.jpg",
    "url" : "anime-html/one piece-main/one piece-main.php",
    "gener" : "",
},
{
  "title_anime" :"Zoids Wild",
  "episode" :5,
  "image" :"anime_image/Zoids Wild.jpg",
    "url" : "anime-html/Zoids Wild-main/Zoids Wild-main.php",
    "gener" : "",
},
{
  "title_anime" :"planet with",
  "episode" :6,
  "image" :"anime_image/planet with.jpg",
    "url" : "anime-html/planet with-main/planet with-main.php",
    "gener" : "",
},
{
  "title_anime" :"Tsukumogami Kashimasu",
  "episode" :4,
  "image" :"anime_image/Tsukumogami Kashimasu.jpg",
    "url" : "anime-html/Tsukumogami Kashimasu-main/Tsukumogami Kashimasu-main.php",
    "gener" : "",
},
{
  "title_anime" :"Pokemon Sun & Moon",
  "episode" :86,
  "image" :"anime_image/Pokemon Sun & Moon.jpg",
    "url" : "anime-html/Pokemon Sun & Moon-main/Pokemon Sun & Moon-main.php",
    "gener" : "",
},

{
  "title_anime" :"persona 5 the animation",
  "episode" :19,
  "image" :"anime_image/persona 5.jpg",
    "url" : "anime-html/persona 5 the animation-main/persona 5 the animation-main.php",
    "gener" : "",
},
{
  "title_anime" :"Hyakuren no Haou to Seiyaku no Valkyria",
  "episode" :6,
  "image" :"anime_image/Hyakuren no Haou to Seiyaku no Valkyria.jpg",
    "url" : "anime-html/Hyakuren no Haou to Seiyaku no Valkyria-main/Hyakuren no Haou to Seiyaku no Valkyria-main.php",
    "gener" : "",
},
{
  "title_anime" :"Yuragi sou no Yuuna san",
  "episode" :5,
  "image" :"anime_image/Yuragi sou no Yuuna san.jpg",
    "url" : "anime-html/Yuragi sou no Yuuna san-main/Yuragi sou no Yuuna san-main.php",
    "gener" : "",
},
{
  "title_anime" :"Major 2nd (TV)",
  "episode" :19,
  "image" :"anime_image/Major 2nd (TV).jpg",
    "url" : "anime-html/Major 2nd (TV)-main/Major 2nd (TV)-main.php",
    "gener" : "",
},
{
  "title_anime" :"Boku no Hero Academia 3rd Season",
  "episode" :18,
  "image" :"anime_image/boku.jpg",
    "url" : "anime-html/Boku no Hero Academia 3rd Season-main/Boku no Hero Academia 3rd Season-main.php",
},
{
  "title_anime" :"Sunoharasou no Kanrinin san",
  "episode" :6,
  "image" :"anime_image/Sunoharasou no Kanrinin san.jpg",
    "url" : "anime-html/Sunoharasou no Kanrinin san-main/Sunoharasou no Kanrinin san-main.php",
    "gener" : "",
},
{
  "title_anime" :"Nobunaga no Shinobi  Anegawa Ishiyama Hen",
  "episode" :19,
  "image" :"anime_image/Nobunaga no Shinobi  Anegawa Ishiyama Hen.jpg",
    "url" : "anime-html/Nobunaga no Shinobi  Anegawa Ishiyama Hen-main/Nobunaga no Shinobi  Anegawa Ishiyama Hen-main.php",
    "gener" : "",
},
{
  "title_anime" :"Grand Blue",
  "episode" :5,
  "image" :"anime_image/Grand Blue.jpg",
    "url" : "anime-html/Grand Blue-main/Grand Blue-main.php",
    "gener" : "",
},
{
  "title_anime" :"Akkun to Kanojo",
  "episode" :18,
  "image" :"anime_image/akkun-to-kanojo.jpg",
    "url" : "anime-html/Akkun to Kanojo/Akkun to Kanojo-main.php",
    "gener" : "",
},
{
  "title_anime" :"Muhyo to Rouji no Mahouritsu Soudan Jimusho",
  "episode" :2,
  "image" :"anime_image/Muhyo to Rouji no Mahouritsu Soudan Jimusho.jpg",
    "url" : "anime-html/Muhyo to Rouji no Mahouritsu Soudan Jimusho-main/Muhyo to Rouji no Mahouritsu Soudan Jimusho-main.php",
    "gener" : "",
},
{
  "title_anime" :"Harukana Receive",
  "episode" :6,
  "image" :"anime_image/Harukana Receive.jpg",
    "url" : "anime-html/Harukana Receive-main/Harukana Receive-main.php",
    "gener" : "",
},
{
  "title_anime" :"Satsuriku no Tenshi",
  "episode" :5,
  "image" :"anime_image/Satsuriku no Tenshi.jpg",
    "url" : "anime-html/Satsuriku no Tenshi-main/Satsuriku no Tenshi-main.php",
    "gener" : "",
},
{
  "title_anime" :"Banana Fish",
  "episode" :7,
  "image" :"anime_image/Banana Fish.jpg",
    "url" : "anime-html/Banana Fish-main/Banana Fish-main.php",
    "gener" : "",
},
{
  "title_anime" :"Shichisei no Subaru",
  "episode" :7,
  "image" :"anime_image/Shichisei no Subaru.jpg",
    "url" : "anime-html/Shichisei no Subaru-main/Shichisei no Subaru-main.php",
    "gener" : "",
},
{
  "title_anime" :"Isekai Maou to Shoukan Shoujo no Dorei Majutsu",
  "episode" :6,
  "image" :"anime_image/Isekai Maou to Shoukan Shoujo no Dorei Majutsu.jpg",
    "url" : "anime-html/Isekai Maou to Shoukan Shoujo no Dorei Majutsu-main/Isekai Maou to Shoukan Shoujo no Dorei Majutsu-main.php",
    "gener" : "",
},
{
  "title_anime" :"Captain Tsubasa (2018)",
  "episode" :20,
  "image" :"anime_image/Captain Tsubasa (2018).jpg",
    "url" : "anime-html/Captain Tsubasa (2018)-main/Captain Tsubasa (2018)-main.php",
    "gener" : "",
},
{
  "title_anime" :"Boruto Naruto Next Generations",
  "episode" :69,
  "image" :"anime_image/boruto.jpg",
    "url" : "anime-html/Boruto Naruto Next Generations-main/Boruto Naruto Next Generations-main.php",
    "gener" : "",
},
{
  "title_anime" :"Steins;Gate 0",
  "episode" :17,
  "image" :"anime_image/Steins;Gate 0.jpg",
    "url" : "anime-html/Steins;Gate 0-main/Steins;Gate 0-main.php",
    "gener" : "",
},
{
  "title_anime" :"Layton Mystery Tanteisha Katri no Nazotoki File",
  "episode" :18,
  "image" :"anime_image/Layton Mystery Tanteisha Katri no Nazotoki File.jpg",
    "url" : "anime-html/Layton Mystery Tanteisha Katri no Nazotoki File-main/Layton Mystery Tanteisha Katri no Nazotoki File-main.php",
    "gener" : "",
},
{
  "title_anime" :"Yu Gi Oh! VRAINS",
  "episode" :64,
  "image" :"anime_image/Yu Gi Oh! VRAINS.jpg",
    "url" : "anime-html/Yu Gi Oh! VRAINS-main/Yu Gi Oh! VRAINS-main.php",
    "gener" : "",
},
{
  "title_anime" :"BLACK CLOVER (TV)",
  "episode" :44,
  "image" :"anime_image/Black Clover (TV).jpg",
    "url" : "anime-html/BLACK CLOVER (TV)-main/BLACK CLOVER (TV)-main.php",
    "gener" : "",
},
{
  "title_anime" :"Uchuu Senkan Yamato 2202 Ai no Senshi-tachi",
  "episode" :18,
  "image" :"anime_image/Uchuu Senkan Yamato 2202 Ai no Senshi-tachi.jpg",
    "url" : "anime-html/Uchuu Senkan Yamato 2202 Ai no Senshi-tachi-main/Uchuu Senkan Yamato 2202 Ai no Senshi-tachi-main.php",
    "gener" : "",
},
{
  "title_anime" :"lupin lll part 5",
  "episode" :18,
  "image" :"anime_image/lupin.jpg",
    "url" : "anime-html/lupin lll part 5-main/lupin lll part 5-main.php",
    "gener" : "",
},
{
  "title_anime" :"Overload III",
  "episode" :5,
  "image" :"anime_image/Overload III.jpg",
    "url" : "anime-html/Overload III-main/Overload III-main.php",
    "gener" : "",
},
{
  "title_anime" :"Wakaokami wa Shougak",
  "episode" :11,
  "image" :"anime_image/Wakaokami wa Shougak.jpg",
    "url" : "anime-html/Wakaokami wa Shougak-main/Wakaokami wa Shougak-main.php",
    "gener" : "",
},
{
  "title_anime" :"Hataraku Saibou (TV)",
  "episode" :5,
  "image" :"anime_image/Hataraku Saibou (TV).jpg",
    "url" : "anime-html/Hataraku Saibou (TV)-main/Hataraku Saibou (TV)-main.php",
    "gener" : "",
},
{
  "title_anime" :"Jashin chan Dropkick",
  "episode" :5,
  "image" :"anime_image/Jashin chan Dropkick.jpg",
    "url" : "anime-html/Jashin chan Dropkick-main/Jashin chan Dropkick-main.php",
    "gener" : "",
},
{
  "title_anime" :"Gintama Shirogane no Tamashii hen 2",
  "episode" :5,
  "image" :"anime_image/Gintama Shirogane no Tamashii hen 2.jpg",
    "url" : "anime-html/Gintama Shirogane no Tamashii hen 2-main/Gintama Shirogane no Tamashii hen 2-main.php",
    "gener" : "",
},
{
  "title_anime" :"Kakuriyo no Yadomeshi",
  "episode" :19,
  "image" :"anime_image/Kakuriyo no Yadomeshi.jpg",
    "url" : "anime-html/Kakuriyo no Yadomeshi-main/Kakuriyo no Yadomeshi-main.php",
    "gener" : "",
},
{
  "title_anime" :"Shingeki no Kyojin Season 3",
  "episode" :3,
  "image" :"anime_image/Shingeki no Kyojin Season 3.jpg",
    "url" : "anime-html/Shingeki no Kyojin Season 3-main/Shingeki no Kyojin Season 3-main.php",
    "gener" : "",
},
{
  "title_anime" :"hanebado!",
  "episode" :6,
  "image" :"anime_image/hanebado!.jpg",
    "url" : "anime-html/hanebado!-main/hanebado!-main.php",
    "gener" : "",
},
{
  "title_anime" :"Island",
  "episode" :6,
  "image" :"anime_image/Island.jpg",
    "url" : "anime-html/Island-main/Island-main.php",
    "gener" : "",
},
{
  "title_anime" :"detective conan",
  "episode" :910,
  "image" :"anime_image/detective conan.jpg",
    "url" : "anime-html/detective conan-main/detective conan-main.php",
    "gener" : "",
},
{
  "title_anime" :"Free! Dive to the Future",
  "episode" :6,
  "image" :"anime_image/Free! Dive to the Future.jpg",
    "url" : "anime-html/Free! Dive to the Future-main/Free! Dive to the Future-main.php",
    "gener" : "",
},
{
  "title_anime" :"Isekai Izakaya Koto Aitheria no Izakaya Nobu",
  "episode" :19,
  "image" :"anime_image/isekai-izakaya-koto-aitheria-no.jpg",
    "url" : "anime-html/Isekai Izakaya Koto Aitheria no Izakaya Nobu-main/Isekai Izakaya Koto Aitheria no Izakaya Nobu-main.php",
    "gener" : "",
},
{
  "title_anime" :"Dragon Ball Heroes",
  "episode" :2,
  "image" :"anime_image/Dragon Ball Heroes.jpg",
    "url" : "anime-html/Dragon Ball Heroes-main/Dragon Ball Heroes-main.php",
    "gener" : "",
},
{
  "title_anime" :"3D Kanojo Real Girl",
  "episode" :12,
  "image" :"anime_image/3D Kanojo Real Girl.jpg",
    "url" : "anime-html/3D Kanojo Real Girl-main/3D Kanojo Real Girl-main.php",
    "gener" : "",
},
{
  "title_anime" :"Alice or Alice Siscon Niisan to Futago no Imouto",
  "episode" :12,
  "image" :"anime_image/Alice or Alice Siscon Niisan to Futago no Imouto.jpg",
    "url" : "anime-html/Alice or Alice Siscon Niisan to Futago no Imouto-main/Alice or Alice Siscon Niisan to Futago no Imouto-main.php",
    "gener" : "",
},
{
  "title_anime" :"Binan Koukou Chikyuu Boueibu Happy Kiss!",
  "episode" :12,
  "image" :"anime_image/Binan Koukou Chikyuu Boueibu Happy Kiss!.jpg",
    "url" : "anime-html/Binan Koukou Chikyuu Boueibu Happy Kiss!-main/Binan Koukou Chikyuu Boueibu Happy Kiss!-main.php",
    "gener" : "",
},
{
  "title_anime" :"Boku no Hero Academia 2nd Season",
  "episode" :25,
  "image" :"anime_image/Boku no Hero Academia 2nd Season.jpg",
    "url" : "anime-html/Boku no Hero Academia 2nd Season-main/Boku no Hero Academia 2nd Season-main.php",
    "gener" : "",
},


{
  "title_anime" :"Butlers Chitose Momotose Monogatari",
  "episode" :12,
  "image" :"anime_image/Butlers Chitose Momotose Monogatari.jpg",
    "url" : "anime-html/Butlers Chitose Momotose Monogatari-main/Butlers Chitose Momotose Monogatari-main.php",
    "gener" : "",
},
{
  "title_anime" :"Caligula",
  "episode" :12,
  "image" :"anime_image/caligula.jpg",
    "url" : "anime-html/Caligula-main/Caligula-main.php",
    "gener" : "",
},

{  "title_anime" :"Cardcaptor Sakura Clear Card hen",
  "episode" :22,
  "image" :"anime_image/Cardcaptor Sakura Clear Card hen.jpg",
    "url" : "anime-html/Cardcaptor Sakura Clear Card hen-main/Cardcaptor Sakura Clear Card hen-main.php",
    "gener" : "",
},
{
  "title_anime" :"Comic Girls",
  "episode" :12,
  "image" :"anime_image/Comic Girls.jpg",
    "url" : "anime-html/Comic Girls-main/Comic Girls-main.php",
    "gener" : "",
},

{
  "title_anime" :"Cutie Honey Universe",
  "episode" :12,
  "image" :"anime_image/Cutie Honey Universe.jpg",
    "url" : "anime-html/Cutie Honey Universe-main/Cutie Honey Universe-main.php",
    "gener" : "",
},
{
  "title_anime" :"Darling in the FranXX",
  "episode" :24,
  "image" :"anime_image/Darling in the FranXX.jpg",
    "url" : "anime-html/Darling in the FranXX-main/Darling in the FranXX-main.php",
    "gener" : "",
},
{
  "title_anime" :"devils line",
  "episode" :12,
  "image" :"anime_image/devils line.jpg",
    "url" : "anime-html/devils line-main/devils line-main.php",
    "gener" : "",
},
{
  "title_anime" :"Dorei-ku The Animation",
  "episode" :12,
  "image" :"anime_image/Dorei-ku The Animation.jpg",
    "url" : "anime-html/Dorei-ku The Animation-main/Dorei-ku The Animation-main.php",
    "gener" : "",
},
{
  "title_anime" :"Full Metal Panic! Invisible Victory",
  "episode" :12,
  "image" :"anime_image/Full Metal Panic! Invisible Victory.jpg",
    "url" : "anime-html/Full Metal Panic! Invisible Victory-main/Full Metal Panic! Invisible Victory-main.php",
    "gener" : "",
},
{
  "title_anime" :"Fumikiri Jikan",
  "episode" :12,
  "image" :"anime_image/Fumikiri Jikan.jpg",
    "url" : "anime-html/Fumikiri Jikan-main/Fumikiri Jikan-main.php",
    "gener" : "",
},
{
  "title_anime" :"Ginga Eiyuu Densetsu  Die Neue These - kaikou",
  "episode" :12,
  "image" :"anime_image/Ginga Eiyuu Densetsu  Die Neue These - kaikou.jpg",
    "url" : "anime-html/Ginga Eiyuu Densetsu  Die Neue These - kaikou-main/Ginga Eiyuu Densetsu  Die Neue These - kaikou-main.php",
    "gener" : "",
},
{
  "title_anime" :"Golden Kamuy",
  "episode" :12,
  "image" :"anime_image/Golden Kamuy.jpg",
    "url" : "anime-html/Golden Kamuy-main/Golden Kamuy-main.php",
    "gener" : "",
},
{
  "title_anime" :"grancrest senki",
  "episode" :24,
  "image" :"anime_image/grancrest.jpg",
    "url" : "anime-html/grancrest senki-main/grancrest senki-main.php",
    "gener" : "",
},
{
  "title_anime" :"Gurazeni",
  "episode" :12,
  "image" :"anime_image/gurazeni.jpg",
    "url" : "anime-html/Gurazeni/Gurazeni-main.php",
    "gener" : "",
},
{
  "title_anime" :"high school dxd hero",
  "episode" :12,
  "image" :"anime_image/high_school.jpg",
    "url" : "anime-html/high school dxd hero-main/high school dxd hero-main.php",
    "gener" : "",
},
{
  "title_anime" :"Hinamatsuri",
  "episode" :12,
  "image" :"anime_image/hinamatsuri.jpg",
    "url" : "anime-html/Hinamatsuri-main/Hinamatsuri-main.php",
    "gener" : "",
},
{
  "title_anime" :"Hitori no Shita_ The Outcast 2nd Season",
  "episode" :24,
  "image" :"anime_image/Hitori no Shita_ The Outcast 2nd Season.jpg",
    "url" : "anime-html/Hitori no Shita_ The Outcast 2nd Season-main/Hitori no Shita_ The Outcast 2nd Season-main.php",
    "gener" : "",
},
{
  "title_anime" :"Hoozuki no Reitetsu 2nd Season Sono Ni",
  "episode" :13,
  "image" :"anime_image/Hoozuki no Reitetsu 2nd Season Sono Ni.jpg",
    "url" : "anime-html/Hoozuki no Reitetsu 2nd Season Sono Ni-main/Hoozuki no Reitetsu 2nd Season Sono Ni-main.php",
    "gener" : "",
},
{
  "title_anime" :"Jewelpet attack chance!",
  "episode" :3,
  "image" :"anime_image/Jewelpet attack chance!.jpg",
    "url" : "anime-html/Jewelpet attack chance!-main/Jewelpet attack chance!-main.php",
    "gener" : "",
},

{
  "title_anime" :"Kiratto pri chan",
  "episode" :8,
  "image" :"anime_image/KIRATTO PRI CHAN.jpg",
    "url" : "anime-html/Kiratto pri chan-main/Kiratto pri chan-main.php",
    "gener" : "",
},
{
  "title_anime" :"Last Period Owarinaki Rasen no Monogatari",
  "episode" :12,
  "image" :"anime_image/Last Period Owarinaki Rasen no Monogatari.jpg",
    "url" : "anime-html/Last Period Owarinaki Rasen no Monogatari-main/Last Period Owarinaki Rasen no Monogatari-main.php",
    "gener" : "",
},
{
  "title_anime" :"Lostorage Conflated WIXOSS",
  "episode" :12,
  "image" :"anime_image/Lostorage Conflated WIXOSS.jpg",
    "url" : "anime-html/Lostorage Conflated WIXOSS-main/Lostorage Conflated WIXOSS-main.php",
    "gener" : "",
},

{
  "title_anime" :"Mahou Shoujo Ore",
  "episode" :12,
  "image" :"anime_image/Mahou Shoujo Ore.jpg",
    "url" : "anime-html/Mahou Shoujo Ore-main/Mahou Shoujo Ore-main.php",
    "gener" : "",
},
{
  "title_anime" :"Mahou Shoujo Site",
  "episode" :12,
  "image" :"anime_image/Mahou Shoujo Site.jpg",
    "url" : "anime-html/Mahou Shoujo Site-main/Mahou Shoujo Site-main.php",
    "gener" : "",
},

{
  "title_anime" :"megalo box",
  "episode" :13,
  "image" :"anime_image/megalo.jpg",
    "url" : "anime-html/megalo box-main/megalo box-main.php",
    "gener" : "",
},
{
  "title_anime" :"Mobile siut gundam the origin",
  "episode" :6,
  "image" :"anime_image/Mobile siut gundam the origin.jpg",
    "url" : "anime-html/Mobile siut gundam the origin-main/Mobile siut gundam the origin-main.php",
    "gener" : "",
},
{
  "title_anime" :"nanatsu-no-taizai-imashime-no-fukkatsu",
  "episode" :24,
  "image" :"anime_image/nanatsu.jpg",
    "url" : "anime-html/nanatsu-no-taizai-imashime-no-fukkatsu-main/nanatsu-no-taizai-imashime-no-fukkatsu-main.php",
    "gener" : "",
},
{
  "title_anime" :"One Punch Man Road To Be Hero",
  "episode" :1,
  "image" :"anime_image/One Punch Man Road To Be Hero.jpg",
    "url" : "anime-html/One Punch Man Road To Be Hero-main/One Punch Man Road To Be Hero-main.php",
    "gener" : "",
},
{
  "title_anime" :"One Punch Man Specials",
  "episode" : 6,
  "image" :"anime_image/One Punch Man Specials.jpg",
    "url" : "anime-html/One Punch Man Specials-main/One Punch Man Specials-main.php",
    "gener" : "",
},
{
  "title_anime" :"One Punch Man",
  "episode" :12,
  "image" :"anime_image/One Punch Man.jpg",
    "url" : "anime-html/One Punch Man-main/One Punch Man-main.php",
    "gener" : "",
},
{
  "title_anime" :"Piano no Mori (TV)",
  "episode" :12,
  "image" :"anime_image/Piano no Mori (TV).jpg",
    "url" : "anime-html/Piano no Mori (TV)-main/Piano no Mori (TV)-main.php",
    "gener" : "",
},
{
  "title_anime" :"Rang Wo Men Shao Ba",
  "episode" :2,
  "image" :"anime_image/Rang Wo Men Shao Ba.jpg",
    "url" : "anime-html/Rang Wo Men Shao Ba-main/Rang Wo Men Shao Ba-main.php",
    "gener" : "",
},
{
  "title_anime" :"Rokuhoudou Yotsuiro biyori",
  "episode" :12,
  "image" :"anime_image/Rokuhoudou Yotsuiro biyori.jpg",
    "url" : "anime-html/Rokuhoudou Yotsuiro biyori-main/Rokuhoudou Yotsuiro biyori-main.php",
    "gener" : "",
},
{
  "title_anime" :"Saiki Kusuo no -nan (TV) 2",
  "episode" :24,
  "image" :"anime_image/Saiki Kusuo no -nan (TV) 2.jpg",
    "url" : "anime-html/Saiki Kusuo no -nan (TV) 2-main/Saiki Kusuo no -nan (TV) 2-main.php",
    "gener" : "",
},
{
  "title_anime" :"Saredo Tsumibito wa Ryuu to Odoru",
  "episode" :12,
  "image" :"anime_image/Saredo Tsumibito wa Ryuu to Odoru.jpg",
    "url" : "anime-html/Saredo Tsumibito wa Ryuu to Odoru-main/Saredo Tsumibito wa Ryuu to Odoru-main.php",
    "gener" : "",
},
{
  "title_anime" :"Shiyan Pin Jiating",
  "episode" :4,
  "image" :"anime_image/shiyan pin jiating.jpg",
    "url" : "anime-html/Shiyan Pin Jiating-main/Shiyan Pin Jiating-main.php",
    "gener" : "",
},
{
  "title_anime" :"Shokugeki no Souma San no Sara - Toutsuki Ressha-hen",
  "episode" :12,
  "image" :"anime_image/Shokugeki no Souma San no Sara - Toutsuki Ressha-hen.jpg",
    "url" : "anime-html/Shokugeki no Souma San no Sara - Toutsuki Ressha-hen-main/Shokugeki no Souma San no Sara - Toutsuki Ressha-hen-main.php",
    "gener" : "",
},
{
  "title_anime" :"Souten no Ken ReGenesis",
  "episode" :12,
  "image" :"anime_image/Souten no Ken ReGenesis.jpg",
    "url" : "anime-html/Souten no Ken ReGenesis-main/Souten no Ken ReGenesis-main.php",
    "gener" : "",
},

{
  "title_anime" :"Sword Art Online Alternative Gun Gale Online",
  "episode" :12,
  "image" :"anime_image/sword_art.jpg",
    "url" : "anime-html/Sword Art Online Alternative Gun Gale Online-main/Sword Art Online Alternative Gun Gale Online-main.php",
    "gener" : "",
},
{
  "title_anime" :"Tachibanakan Triangle",
  "episode" :12,
  "image" :"anime_image/Tachibanakan Triangle.jpg",
    "url" : "anime-html/Tachibanakan Triangle-main/Tachibanakan Triangle-main.php",
    "gener" : "",
},
{
  "title_anime" :"Tada-kun wa Koi wo Shinai",
  "episode" :13,
  "image" :"anime_image/Tada-kun wa Koi wo Shinai.jpg",
    "url" : "anime-html/Tada-kun wa Koi wo Shinai-main/Tada-kun wa Koi wo Shinai-main.php",
    "gener" : "",
},
{
  "title_anime" :"To Be Heroine",
  "episode" :7,
  "image" :"anime_image/To Be Heroine.jpg",
    "url" : "anime-html/To Be Heroine-main/To Be Heroine-main.php",
    "gener" : "",
},
{
  "title_anime" :"Tokyo Ghoul re",
  "episode" :12,
  "image" :"anime_image/Tokyo Ghoul re.jpg",
    "url" : "anime-html/Tokyo Ghoul re-main/Tokyo Ghoul re-main.php",
    "gener" : "",
},
{
  "title_anime" :"Uchuu Senkan Tiramisu",
  "episode" :13,
  "image" :"anime_image/Uchuu Senkan Tiramisu.jpg",
    "url" : "anime-html/Uchuu Senkan Tiramisu-main/Uchuu Senkan Tiramisu-main.php",
    "gener" : "",
},
{
  "title_anime" :"Wotaku ni Koi wa Muzukashii",
  "episode" :11,
  "image" :"anime_image/wotaku.jpg",
    "url" : "anime-html/Wotaku ni Koi wa Muzukashii-main/Wotaku ni Koi wa Muzukashii-main.php",
    "gener" : "",
},

{
  "title_anime" :"Haikyuu!! Second Season",
  "image" :"anime_image/Haikyuu!! Second Season.jpg",
    "url" : "anime-html/Haikyuu!! Second Season-main/Haikyuu!! Second Season-main.php",
    "gener" : "",
},
{
  "title_anime" :"Youkai Watch Shadow side",
  "episode" :14,
  "image" :"anime_image/Youkai Watch Shadow side.jpg",
    "url" : "anime-html/Youkai Watch Shadow side-main/Youkai Watch Shadow side-main.php",
    "gener" : "",
}

];
$('#myInput').keyup(function(){
            var searchField = $(this).val();
      if(searchField === '')  {
        $('#results').html('');
        return;
      }
      
            var regex = new RegExp(searchField, "i");
            var output = '<tr class="position">';
            var count = 1;
        $.each(data, function(key, val){
        if ( (val.title_anime.search(regex) != -1)) {
          output += '<td >';
          output += '<a href="'+ val.url +'"><img class="image_general" src="'+val.image+'" alt="'+ val.title_anime +'" />';
          output += '<p class="text_position">' + val.title_anime + '</p>';
          output += '</a>';
          output += '</td>';
          if(count%1 == 0){
          output += '</tr> <div >'
          }
          count++;
        }
        });
        output += '</div>';
        $('#results').html(output);
        });

});

  
</script>